"""Updated loans

Revision ID: 2bb8c7cabd11
Revises: c417aa3ab91c
Create Date: 2024-12-09 19:32:32.676145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb8c7cabd11'
down_revision = 'c417aa3ab91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('term', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('monthly_payment', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('remaining_balance', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('next_payment_due', sa.DateTime(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.drop_column('due_date')
        batch_op.drop_column('principal')
        batch_op.drop_column('balance')
        batch_op.drop_column('term_years')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('term_years', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('balance', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('principal', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('due_date', sa.DATETIME(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('next_payment_due')
        batch_op.drop_column('remaining_balance')
        batch_op.drop_column('monthly_payment')
        batch_op.drop_column('term')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
