"""Added net_worth to users

Revision ID: a49dc0f9ca63
Revises: 2bb8c7cabd11
Create Date: 2024-12-09 20:15:17.727288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49dc0f9ca63'
down_revision = '2bb8c7cabd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_worth', sa.Integer(), nullable=False, server_default='10000'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('net_worth')

    # ### end Alembic commands ###
